#!/bin/bash
SCRIPTDIR="$(readlink -fm "$(dirname $0)")"
F=""
for i in "${SCRIPTDIR}/mips2mars_2.10-0.1-SNAPSHOT.min.jar" "${SCRIPTDIR}/target/scala-2.10/mips2mars_2.10-0.1-SNAPSHOT.min.jar" ; do
    if [[ -f "$i" ]] ; then
        F="$i"
    fi
done
test -z "$F" && { echo "jar no encontrado" 2>&1 ; exit 1 ; }
exec java -jar $F $@
