#!/bin/bash

SCRIPTS_DIR="$(dirname "$(realpath "$0")")"

JAR_FILE="riscv2rars.jar"
(
    cd "${SCRIPTS_DIR}/"
    make -q "${JAR_FILE}" &> /dev/null || {
        if which sbt &> /dev/null ; then
            echo "jar no encontrado o desactualizado, compilando…" 2>&1 
            make --quiet "${JAR_FILE}"
        else
            echo "sbt no encontrado, no se puede compilar riscv2rars" 2>&1 
            echo "sbt se puede obtener de https://www.scala-sbt.org/" 2>&1 
            exit 1
        fi
    }
) || exit $?

#MEM="$(printf "24576\n$(($(grep "MemTotal:" /proc/meminfo | head -n1 | tr -s " " | cut -d" " -f2) * 4 / 7 / 1024))\n" | sort -n | head -n1)"
#export JAVA_OPTS="${JAVA_OPTS:-Xmx${MEM}m}"

exec java -jar "${SCRIPTS_DIR}/${JAR_FILE}" "$@"

